title: Koffee's Corner
email: KoffeeJava@tuta.io
description: >- # this means to ignore newlines until "baseurl:"
 The coolest website on the internet!
 No, really, it is.
baseurl:
domain: koffeejava.uw
url: "https://koffeejava.us" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KoffeeJava

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
